### ISSUE TITLE
Remove settings.mangui.setup.scss

### ISSUE THREAD

**Issue by MangopearUK** [mangopear-framework/core-css#10]
File: [`/settings/_settings.mangui.setup.scss`](https://github.com/MangopearUK/MangUI-Framework/blob/master/resources/css/sass/settings/_settings.mangui.setup.scss)

### Changes to make:

- [ ] Remove from system
- [ ] Rename other variable references to fix compile issues

**Comment by CreativeFruitBowl** [comment]
Closing as no longer relevant and there is no opportunity to fix.
