### ISSUE TITLE
Add sass-mq for media queries in framework

### ISSUE THREAD

**Issue by MangopearUK** [mangopear-framework/core-css#11]
See [`sass-mq`](https://github.com/sass-mq/sass-mq) for more details about integration.

- [x] Include as `dev-dependency` in `package.json`
- [ ] Set up default breakpoint names, ensuring they're overwritable by frameworks
- [ ] Document integration

**Comment by CreativeFruitBowl** [comment]
Closing as no longer relevant and there is no opportunity to fix.
