### ISSUE TITLE
Refactor settings.mangui.defaults.scss

### ISSUE THREAD

**Issue by MangopearUK** [mangopear-framework/core-css#9]
File: [`/settings/_settings.mangui.default.scss`](https://github.com/MangopearUK/MangUI-Framework/blob/master/resources/css/sass/settings/_settings.mangui.default.scss)

### Changes to make:

- [ ] Rename file to new file naming conventions
- [ ] Add settings for vertical rhythm
- [ ] Remove responsive styles as they're not used
- [ ] Add support for `sass-mq` media queries
- [ ] Remove old media query size references (create package to map old settings to new)
- [ ] Filter through other sizing variables to decide what's needed and what's not
- [ ] Provide inline documentation
- [ ] Document settings

**Comment by CreativeFruitBowl** [comment]
Closing as no longer relevant and there is no opportunity to fix.
